### ISSUE TITLE
Excel - Fatal error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by morningtoast** [jpweeks/grunt-csv-json#1]
If I save an Excel sheet as a CSV the task throws an error:
`Fatal error: Cannot read property '0' of undefined`

However, if I take that same CSV data and paste it into a new plain text (non-Excel) CSV, the task runs just fine. It's like Excel is doing something to the CSV when it saves but there's no extra data/characters showing in the CSV to suggest otherwise.

Downloading as CSV from Google Docs works without error, just seems to be when using Excel.

**Comment by milcktoast** [comment]
Can you provide an example of the csv format which is causing an error?
It might be an issue with [node-csv-parse](https://github.com/wdavidw/node-csv-parse), which is what this task uses to parse csv files.

**Comment by morningtoast** [comment]
Hello...sorry for the delayed reply. I think in order to see the fail you'll need to try an actual file. When you look at the CSV in a text editor there is nothing different about the format, it looks like it should work. I put a CSV that I saved out of Excel up on Dropbox, feel free to download and try it. Or if you have Excel, do a "Save As" with CSV and see if it gives you an error.

Dropbox link: https://www.dropbox.com/s/7jjbw8whi0u6o08/msexample.csv?dl=0

Sorry I can't provide more info or details. It feels like an odd bug to me and could very well not be a bug with your plugin but the base node module, as you mentioned. Any suggestions or thoughts are appreciated. Thanks for your help and thanks for a handy plugin. Thanks!

**Comment by milcktoast** [comment]
I'm not sure what the issue is, I added tests for number values as well as the exact document you provided, and they all pass. 646b195d1461088eb01d9dc6a3304b840a323674

**Comment by morningtoast** [comment]
Thanks for giving it a shot. I'll just have to keep poking around to see where the fail is on my end. My gut says it's some sort of encoding thing but don't know how to prove it otherwise. If I discover something I'll post back or try to let you know, just in case others come across it. Thanks!
